name: Deploy book with Python, SPARQL, and R

on:
  workflow_run:
    workflows: ["Update Metadata"]
    types:
      - completed
    branches:
      - main

# This job installs dependencies, builds the book, and deploys it to GitHub Pages
# only runs if "Update Metadata" workflow is successful
jobs:
  setup-kernels:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        kernel: [python, r]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Python setup
    - name: Set up Python
      if: matrix.kernel == 'python'
      uses: actions/setup-python@v5
      with:
        python-version-file: '.python-version'
        cache: pip

    - name: Install Python dependencies
      if: matrix.kernel == 'python'
      run: |
        pip install -r requirements.txt

    - name: Install SPARQL kernel
      if: matrix.kernel == 'python'
      run: |
        jupyter sparqlkernel install --user

    # R setup
    - name: Set up R
      if: matrix.kernel == 'r'
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      if: matrix.kernel == 'r'
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache: true
        cache-version: 2
        packages: |
          any::tidyverse
          any::IRkernel
        install-pandoc: false
        install-quarto: false

    - name: Set up IRkernel
      if: matrix.kernel == 'r'
      run: |
        IRkernel::installspec(name="ir", displayname="R")
      shell: Rscript {0}

  deploy-book:
    runs-on: ubuntu-latest
    needs: setup-kernels
    permissions:
      pages: write
      id-token: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Re-setup Python for build job
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: '.python-version'
        cache: pip

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    # Re-setup R for build job
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache: true
        cache-version: 2
        packages: |
          any::tidyverse
          any::IRkernel
        install-pandoc: false
        install-quarto: false

    - name: Set up IRkernel
      run: |
        IRkernel::installspec(name="ir", displayname="R")
      shell: Rscript {0}

    # Install SPARQL kernel
    - name: Install SPARQL kernel
      run: |
        jupyter sparqlkernel install --user

    # check all kernels 
    - name: Log all available kernels
      run: |
        jupyter kernelspec list

    # only caches if set up in _config.yml with:
    # execute:
    #   execute_notebooks: cache
    - name: Cache executed notebooks
      uses: actions/cache@v3
      with:
        path: _build/.jupyter_cache
        key: jupyter-book-cache-${{ hashFiles('requirements.txt') }}

    - name: Build the book
      run: |
        jupyter-book build .

    - name: Upload book artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "_build/html"

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
